draw_config:
  layout:
    ortho_layout:
      split: true
      rows: 4
      columns: 6
      thumbs: 5

  append_colon_to_layer_header: false
  draw_key_sides: true

  svg_extra_style: |
    svg.keymap {
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 10px;
      font-weight: bold;
    }
    text.label {
      stroke: #dfdfde;
      stroke-width: 12;
      stroke-linejoin: round;
    }
    rect.combo, rect.combo-separate {
      opacity: 0.95;
      stroke: #c9cccf;
      stroke-width: 0.5;
      fill: #d7eaed;
    }
    path.combo {
      stroke-dasharray: 4, 4;
      stroke-opacity: 0.3;
    }
    rect.held, rect.combo.held {
      fill: #ebdada;
    }

  parse_config:
    preprocess: false
    # 映射你实际上用到的所有绑定
    raw_binding_map:
      "&none": { tap: " ", type: none }
      "&bootloader": { tap: "BOOT" }
      "&mkp LCLK": { tap: "LCLK", hold: "left" }
      "&mkp MCLK": { tap: "MCLK", hold: "mid" }
      "&mkp RCLK": { tap: "RCLK", hold: "right" }
      "&bt BT_SEL 0": { tap: "BT0", hold: "0" }
      "&bt BT_SEL 1": { tap: "BT1", hold: "1" }
      "&bt BT_SEL 2": { tap: "BT2", hold: "2" }
      "&bt BT_CLR": { tap: "CLR" }
      "&mo 1": { tap: "L1", hold: "L1", type: held }
      "&mo 2": { tap: "L2", hold: "L2", type: held }
      "&mo 3": { tap: "L3", hold: "L3", type: held }
      "&mo 4": { tap: "L4", hold: "L4", type: held }
      "&lt 1 ENTER": { tap: "Enter", hold: "L1", type: held }
      "&lt 2 ENTER": { tap: "Enter", hold: "L2", type: held }
      "&lt 3 Z": { tap: "Z", hold: "L3", type: held }
      "&lt 3 SLASH": { tap: "/", hold: "L3", type: held }
      "&kp BACKSPACE": { tap: "Bksp" }
      "&kp ESCAPE": { tap: "Esc" }
      "&kp LEFT_SHIFT": { tap: "LShft" }
      "&kp LEFT_CTRL": { tap: "LCtl" }
      "&kp LEFT_ALT": { tap: "LAlt" }
      "&kp LEFT_WIN": { tap: "Win" }
      "&kp RIGHT_ALT": { tap: "RAlt" }
      "&kp SPACE": { tap: "Spc" }
      "&kp ENTER": { tap: "Ent" }
      "&kp TAB": { tap: "Tab" }
      "&kp DELETE": { tap: "Del" }
      "&kp CAPSLOCK": { tap: "Caps" }
