name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - "config/charybdis.keymap"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Draw keymaps
        run: |
          mkdir -p keymap-drawer
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
            ghcr.io/caksoylar/keymap-drawer \
            keymap parse -z config/charybdis.keymap -c 10 > keymap-drawer/charybdis.yaml
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
            ghcr.io/caksoylar/keymap-drawer \
            keymap draw keymap-drawer/charybdis.yaml -c keymap_drawer.config.yaml > keymap-drawer/charybdis.svg

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "keymap-drawer/*.svg keymap-drawer/*.yaml"
          commit_message: "keymap-drawer render"
